### ISSUE TITLE
Would Love To contribute by Starting with Making the Example.

### ISSUE THREAD

**Issue by hb2708** [instant-solutions/ISTimeline#2]
Hello @andlinger @holzleitner ,

Let me know what is expected in the example would love to contribute.

I also added an sample image let me know how can i help into it.
👍

**Comment by holzleitner** [comment]
Hi @hb2708!

I'll create a simple demo, just to show, that ISTimeline performs well, but feel free to create a extended demo application in a new repo with different timeline configurations (colors, point diameters, etc.)! I will link it in the readme.md 👍 

Thank you 😀

**Comment by sanjeetsuhag** [comment]
@hb2708 I'll work on creating an example app with various styles and configurations of ISTimeline.
