### ISSUE TITLE
scrolling to bottom?

### ISSUE THREAD

**Issue by galileomd** [instant-solutions/ISTimeline#3]
is there a call to scroll to the bottom of the stack?

**Comment by holzleitner** [comment]
Hi!
The timeline view inherits from UIScrollView so you are able to simply call `.setContentOffset(contentOffset: CGPoint, animated: Bool)`.

The following snippet should work 😉 
```swift
let bottom = CGPointMake(0, timeline.contentSize.height - timeline.bounds.size.height)
timeline.setContentOffset(bottom, animated: true)
```
