### ISSUE TITLE
I think you should inherit UITableView or UICollectionView

### ISSUE THREAD

**Issue by huangboju** [instant-solutions/ISTimeline#4]

**Comment by sanjeetsuhag** [comment]
I disagree. If anybody wanted to implement zooming and panning, then the fact that its a subclass of `UITableView` or `UICollectionView` would be a hindrance and reduce flexibility. Unless a proven performance increase is shown, I don't think there is a need to inherit from either of those classes.

**Comment by huangboju** [comment]
(*^__^*)
