### ISSUE TITLE
Updated for Swift 3?

### ISSUE THREAD

**Issue by flamingfusion** [instant-solutions/ISTimeline#5]
I'm interested in using this but it doesn't seem to be compatible for Swift 3 at the moment, will it be updated?

**Comment by holzleitner** [comment]
Hi!
Yep, i'll update the view!
I've added it to my TODO list 👍

**Comment by flamingfusion** [comment]
Great! I'm glad this project is active 👍 😄

**Comment by lou-lan** [comment]
hope project support swift3

**Comment by sanjeetsuhag** [comment]
@holzleitner @lou-lan  @flamingfusion 

I have updated the framework to Swift 3. See [#request](https://github.com/instant-solutions/ISTimeline/pull/6) for more.

**Comment by O16MuhammadAhmedBaig** [comment]
how can i update to swift 3

**Comment by sanjeetsuhag** [comment]
You can use my fork, which is compatible with Swift 3.

https://github.com/sanjeetsuhag/ISTimeline

**Comment by holzleitner** [comment]
Have a look at the release [ISTimeline v0.0.4](https://github.com/instant-solutions/ISTimeline/releases/tag/v1.0.0) 🤙
